package com.sultanagung1.sista.core.accessibility

import androidx.compose.runtime.compositionLocalOf

data class StringsDefinition(
    // App & Identity
    val appTitle: String,
    val schoolName: String = "SMA Islam Sultan Agung 1 Semarang",
    val welcomeGreeting: String,
    val islamicGreeting: String,

    // Navigation Tabs
    val homeTab: String,
    val scheduleTab: String,
    val modulesTab: String,
    val profileTab: String,
    val executiveTab: String,
    val teacherTab: String,
    val parentTab: String,
    val billingTab: String,
    val cbtTab: String = "Ujian CBT",
    val gradesTab: String = "Rapor KKTP",
    val notificationsTab: String = "Pengumuman",
    // FASE 77: guru → "Mengajar" (sesi kelas hari ini); admin/Waka/TU → "Sesi Kelas".
    val teachingTab: String = "Mengajar",
    val classSessionsTab: String = "Sesi Kelas",

    // Settings & Configuration
    val settingsTitle: String,
    val languageTitle: String,
    val themeTitle: String,
    val accessibilityTitle: String,
    val biometricSecurity: String,
    val aboutSchool: String,

    // Authentication & Dialogs
    val logoutButton: String,
    val logoutConfirmTitle: String,
    val logoutConfirmMessage: String,
    val cancelText: String,
    val confirmLogoutText: String,

    // Roles & Badges
    val studentActive: String,
    val teacherBadge: String,
    val principalBadge: String,
    val parentBadge: String,
    val superadminBadge: String,

    // Academic Domain (Kurikulum Merdeka)
    val academicSchedule: String = "Jadwal Pelajaran KBM",
    val academicGrades: String = "Rapor Nilai KKTP",
    val academicCbt: String = "Ujian CBT Online",
    val academicElearning: String = "E-Learning LMS",
    val academicQuestionBank: String = "Bank Soal Terpusat",
    val academicTeachingJournal: String = "Jurnal Mengajar Guru",
    val kktpPassed: String = "Tuntas KKTP",
    val kktpRemedial: String = "Perlu Remedial",

    // Finance Domain
    val billingTitle: String = "Tagihan SPP & Infaq",
    val virtualAccount: String = "BSI Virtual Account",
    val statusPaid: String = "LUNAS • SAH",
    val statusUnpaid: String = "BELUM BAYAR",
    val dueDate: String = "Batas Pembayaran",
    val officialReceipt: String = "Kuitansi Pembayaran Sah",

    // Attendance Domain
    val attendanceTitle: String = "Presensi GPS Kampus",
    val attendancePresent: String = "Hadir di Sekolah",
    val attendanceLate: String = "Terlambat Hadir",
    val attendanceSick: String = "Izin Sakit",
    val attendancePermission: String = "Izin Keperluan",
    val attendanceAbsent: String = "Alpa (Tanpa Keterangan)",

    // Communication Domain
    val chatTitle: String = "Chat Konsultasi Ortu & Guru",
    val notificationsTitle: String,
    val officialCircular: String = "Surat Edaran Resmi",

    // Student Affairs & Services
    val disciplineTitle: String = "Buku Saku Poin Tatib",
    val counselingTitle: String = "Konseling BK Digital",
    val libraryTitle: String = "E-Pustaka Pintar",
    val extracurricularTitle: String = "Ekstrakurikuler & OSIS",
    val achievementsTitle: String = "Portofolio Prestasi Siswa",
    val utbkTitle: String = "Simulasi UTBK / SNBT",
    val uksTitle: String = "UKS & Rekam Medis",

    // Common Actions
    val actionBack: String = "Kembali",
    val actionSave: String = "Simpan",
    val actionConfirm: String = "Konfirmasi",
    val actionSearch: String = "Cari…",
    val actionFilter: String = "Filter",
    val actionRefresh: String = "Muat Ulang",
    val actionDownload: String = "Unduh PDF",
    val actionRetry: String = "Coba Lagi"
)

val IndonesianStrings = StringsDefinition(
    appTitle = "SMA Islam Sultan Agung 1 Semarang",
    schoolName = "SMA Islam Sultan Agung 1 Semarang",
    welcomeGreeting = "Selamat Datang",
    islamicGreeting = "Assalamu'alaikum Warahmatullahi Wabarakatuh",
    homeTab = "Beranda",
    scheduleTab = "Jadwal",
    modulesTab = "74 Modul",
    profileTab = "Profil",
    executiveTab = "Eksekutif",
    teacherTab = "Pendidik",
    parentTab = "Wali Murid",
    billingTab = "Tagihan SPP",
    cbtTab = "Ujian CBT",
    gradesTab = "Rapor KKTP",
    notificationsTab = "Pengumuman",
    teachingTab = "Mengajar",
    classSessionsTab = "Sesi Kelas",
    settingsTitle = "Pengaturan SuperApp",
    languageTitle = "Pengaturan Bahasa",
    themeTitle = "Tema & Mode Gelap",
    accessibilityTitle = "Aksesibilitas & Font Scaling",
    logoutButton = "Keluar dari Akun",
    logoutConfirmTitle = "Konfirmasi Keluar Akun",
    logoutConfirmMessage = "Apakah Anda yakin ingin keluar dari sesi ini?",
    cancelText = "Batal",
    confirmLogoutText = "Ya, Keluar",
    biometricSecurity = "Keamanan Sidik Jari (m-Banking)",
    notificationsTitle = "Notifikasi & Pengumuman Sekolah",
    aboutSchool = "Tentang SMA Islam Sultan Agung 1",
    studentActive = "SISWA AKTIF",
    teacherBadge = "GURU PENDIDIK",
    principalBadge = "KEPALA SEKOLAH",
    parentBadge = "WALI MURID",
    superadminBadge = "SUPERADMIN ULTIMATE",
    academicSchedule = "Jadwal Pelajaran KBM",
    academicGrades = "Rapor Nilai KKTP",
    academicCbt = "Ujian CBT Online",
    academicElearning = "E-Learning LMS",
    academicQuestionBank = "Bank Soal Terpusat",
    academicTeachingJournal = "Jurnal Mengajar Guru",
    kktpPassed = "Tuntas KKTP",
    kktpRemedial = "Perlu Remedial",
    billingTitle = "Tagihan SPP & Infaq",
    virtualAccount = "BSI Virtual Account",
    statusPaid = "LUNAS • SAH",
    statusUnpaid = "BELUM BAYAR",
    dueDate = "Batas Pembayaran",
    officialReceipt = "Kuitansi Pembayaran Sah",
    attendanceTitle = "Presensi GPS Kampus",
    attendancePresent = "Hadir di Sekolah",
    attendanceLate = "Terlambat Hadir",
    attendanceSick = "Izin Sakit",
    attendancePermission = "Izin Keperluan",
    attendanceAbsent = "Alpa (Tanpa Keterangan)",
    chatTitle = "Chat Konsultasi Ortu & Guru",
    officialCircular = "Surat Edaran Resmi",
    disciplineTitle = "Buku Saku Poin Tatib",
    counselingTitle = "Konseling BK Digital",
    libraryTitle = "E-Pustaka Pintar",
    extracurricularTitle = "Ekstrakurikuler & OSIS",
    achievementsTitle = "Portofolio Prestasi Siswa",
    utbkTitle = "Simulasi UTBK / SNBT",
    uksTitle = "UKS & Rekam Medis",
    actionBack = "Kembali",
    actionSave = "Simpan",
    actionConfirm = "Konfirmasi",
    actionSearch = "Cari…",
    actionFilter = "Filter",
    actionRefresh = "Muat Ulang",
    actionDownload = "Unduh PDF",
    actionRetry = "Coba Lagi"
)

val EnglishStrings = StringsDefinition(
    appTitle = "Sultan Agung 1 Islamic High School",
    schoolName = "SMA Islam Sultan Agung 1 Semarang",
    welcomeGreeting = "Welcome",
    islamicGreeting = "Assalamu'alaikum Warahmatullahi Wabarakatuh",
    homeTab = "Home",
    scheduleTab = "Schedule",
    modulesTab = "74 Modules",
    profileTab = "Profile",
    executiveTab = "Executive",
    teacherTab = "Educator",
    parentTab = "Parents",
    billingTab = "Tuition & Fees",
    cbtTab = "CBT Exam",
    gradesTab = "KKTP Grades",
    notificationsTab = "Announcements",
    teachingTab = "Teaching",
    classSessionsTab = "Class Sessions",
    settingsTitle = "SuperApp Settings",
    languageTitle = "Language Settings",
    themeTitle = "Theme & Dark Mode",
    accessibilityTitle = "Accessibility & Font Scaling",
    logoutButton = "Log Out from Account",
    logoutConfirmTitle = "Confirm Sign Out",
    logoutConfirmMessage = "Are you sure you want to log out from this active session?",
    cancelText = "Cancel",
    confirmLogoutText = "Yes, Log Out",
    biometricSecurity = "Fingerprint Security (m-Banking)",
    notificationsTitle = "School Notifications & Announcements",
    aboutSchool = "About SMA Islam Sultan Agung 1",
    studentActive = "ACTIVE STUDENT",
    teacherBadge = "TEACHER / EDUCATOR",
    principalBadge = "SCHOOL PRINCIPAL",
    parentBadge = "PARENT / GUARDIAN",
    superadminBadge = "SUPERADMIN ULTIMATE",
    academicSchedule = "Academic Class Schedule",
    academicGrades = "KKTP Grade Report",
    academicCbt = "Online CBT Examination",
    academicElearning = "E-Learning LMS",
    academicQuestionBank = "Central Question Bank",
    academicTeachingJournal = "Teaching Journal",
    kktpPassed = "Passed KKTP",
    kktpRemedial = "Remedial Required",
    billingTitle = "Tuition & Infaq Billing",
    virtualAccount = "BSI Virtual Account",
    statusPaid = "PAID • VERIFIED",
    statusUnpaid = "UNPAID",
    dueDate = "Due Date",
    officialReceipt = "Official Payment Receipt",
    attendanceTitle = "Campus GPS Attendance",
    attendancePresent = "Present at School",
    attendanceLate = "Late Arrival",
    attendanceSick = "Sick Leave",
    attendancePermission = "Excused Absence",
    attendanceAbsent = "Unexcused Absence",
    chatTitle = "Parent-Teacher Consultation",
    officialCircular = "Official Circular Letter",
    disciplineTitle = "Discipline Pocketbook",
    counselingTitle = "Digital Guidance Counseling",
    libraryTitle = "Smart E-Library",
    extracurricularTitle = "Extracurricular & OSIS",
    achievementsTitle = "Student Achievement Portfolio",
    utbkTitle = "UTBK / SNBT Simulation",
    uksTitle = "School Clinic & Medical Records",
    actionBack = "Back",
    actionSave = "Save",
    actionConfirm = "Confirm",
    actionSearch = "Search…",
    actionFilter = "Filter",
    actionRefresh = "Refresh",
    actionDownload = "Download PDF",
    actionRetry = "Retry"
)

val ArabicStrings = StringsDefinition(
    appTitle = "مدرسة السلطان أجونج 1 الإسلامية الثانوية",
    schoolName = "SMA Islam Sultan Agung 1 Semarang",
    welcomeGreeting = "مرحبًا بكم",
    islamicGreeting = "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ",
    homeTab = "الرئيسية",
    scheduleTab = "الجدول",
    modulesTab = "74 وحدة",
    profileTab = "الملف الشخصي",
    executiveTab = "الإدارة",
    teacherTab = "المعلم",
    parentTab = "ولي الأمر",
    billingTab = "الرسوم الدراسية",
    cbtTab = "اختبار CBT",
    gradesTab = "درجات KKTP",
    notificationsTab = "الإعلانات",
    teachingTab = "التدريس",
    classSessionsTab = "الحصص الدراسية",
    settingsTitle = "إعدادات التطبيق",
    languageTitle = "إعدادات اللغة",
    themeTitle = "المظهر والوضع الداكن",
    accessibilityTitle = "إمكانية الوصول وحجم الخط",
    logoutButton = "تسجيل الخروج من الحساب",
    logoutConfirmTitle = "تأكيد تسجيل الخروج",
    logoutConfirmMessage = "هل أنت متأكد أنك تريد تسجيل الخروج من هذه الجلسة؟",
    cancelText = "إلغاء",
    confirmLogoutText = "نعم، خروج",
    biometricSecurity = "أمان بصمة الإصبع المصرفي",
    notificationsTitle = "الإشعارات والإعلانات المدرسية",
    aboutSchool = "حول مدرسة السلطان أجونج 1",
    studentActive = "طالب نشط",
    teacherBadge = "معلم ومربي",
    principalBadge = "مدير المدرسة",
    parentBadge = "ولي أمر الطالب",
    superadminBadge = "المشرف العام",
    academicSchedule = "الجدول الدراسي للحصص",
    academicGrades = "تقرير درجات KKTP",
    academicCbt = "الاختبارات الإلكترونية CBT",
    academicElearning = "نظام التعلم الإلكتروني LMS",
    academicQuestionBank = "بنك الأسئلة المركزي",
    academicTeachingJournal = "سجل المعلم اليومي",
    kktpPassed = "اجتياز KKTP بنجاح",
    kktpRemedial = "يتطلب برنامج علاجي",
    billingTitle = "فواتير الرسوم والإنفاق",
    virtualAccount = "الحساب الافتراضي BSI",
    statusPaid = "مدفوع • معتمد",
    statusUnpaid = "غير مدفوع",
    dueDate = "تاريخ الاستحقاق",
    officialReceipt = "إيصال الدفع المعتمد",
    attendanceTitle = "تسجيل الحضور عبر GPS",
    attendancePresent = "حاضر في المدرسة",
    attendanceLate = "تأخر في الحضور",
    attendanceSick = "إجازة مرضية",
    attendancePermission = "إذن مسبق",
    attendanceAbsent = "غياب بدون عذر",
    chatTitle = "استشارات أولياء الأمور والمعلمين",
    officialCircular = "التعاميم والخطابات الرسمية",
    disciplineTitle = "دليل نقاط الانضباط المدرسي",
    counselingTitle = "الإرشاد الطلابي الرقمي BK",
    libraryTitle = "المكتبة الإلكترونية الذكية",
    extracurricularTitle = "الأنشطة الموازية ومجلس الطلاب",
    achievementsTitle = "سجل إنجازات الطلاب",
    utbkTitle = "محاكاة اختبارات UTBK / SNBT",
    uksTitle = "الوحدة الصحية والسجل الطبي",
    actionBack = "رجوع",
    actionSave = "حفظ",
    actionConfirm = "تأكيد",
    actionSearch = "بحث…",
    actionFilter = "تصفية",
    actionRefresh = "تحديث",
    actionDownload = "تحميل PDF",
    actionRetry = "إعادة المحاولة"
)

fun getAppStrings(language: AppLanguage): StringsDefinition {
    return when (language) {
        AppLanguage.INDONESIAN -> IndonesianStrings
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.ARABIC -> ArabicStrings
    }
}

val LocalAppStrings = compositionLocalOf { IndonesianStrings }
