param (
    [switch]$DryRun = $false
)

$ErrorActionPreference = "Stop"

Write-Host "======================================"
Write-Host " SISTA Enterprise - Auto Commit & PR"
Write-Host "======================================"

if ($DryRun) {
    Write-Host "[DRY RUN MODE] No changes will be made." -ForegroundColor Yellow
}

# Check for uncommitted changes
$status = git status --porcelain
if ([string]::IsNullOrWhiteSpace($status)) {
    Write-Host "No uncommitted changes found. Exiting."
    exit 0
}

Write-Host "Found uncommitted changes."

# Create a feature branch
$branchName = "feature/auto-update-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
if (-not $DryRun) {
    git checkout -b $branchName main
} else {
    Write-Host "[DRY RUN] Would checkout new branch: $branchName"
}

# Determine commit message based on changed files
$commitMsg = "chore: auto-update various modules"
if ($status -match "ui/") { $commitMsg = "feat(ui): update UI components" }
elseif ($status -match "core/") { $commitMsg = "feat(core): update core logic" }
elseif ($status -match "data/") { $commitMsg = "feat(data): update data layer" }

if (-not $DryRun) {
    git add .
    git commit -m $commitMsg
    git push origin $branchName
    
    # Create PR using gh CLI
    Write-Host "Creating Pull Request..."
    gh pr create --title "$commitMsg" --body "Automated PR generated by GitOps script." --base main --head $branchName
    Write-Host "PR created successfully!" -ForegroundColor Green
} else {
    Write-Host "[DRY RUN] Would commit with message: '$commitMsg'"
    Write-Host "[DRY RUN] Would push to $branchName"
    Write-Host "[DRY RUN] Would create PR"
}
